version: "3.4"
services:
  baserow:
    container_name: baserow
    image: baserow/baserow:1.27.2
    environment:
      BASEROW_PUBLIC_URL: $BASEROW_PUBLIC_URL
    ports:
      - "3000:80"
    volumes:
      - baserow_data:/baserow/data
volumes:
  baserow_data:
